name: article_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  connectivity: ^3.0.6
  dartz: ^0.10.1
  dio: ^5.4.2+1
  equatable: ^2.0.5
  floor: ^1.4.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_screenutil: ^5.9.0
  get_it: ^7.7.0
  go_router: ^13.2.5
  google_fonts: ^6.2.1
  http: ^1.2.1
  internet_connection_checker: ^1.0.0+1
  retrofit: ^4.1.0
  rxdart: ^0.27.7
  shared_preferences: ^2.2.3
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  retrofit_generator: ^8.1.0
  floor_generator: ^1.4.2
  build_runner: ^2.4.9
  mockito: ^5.4.4
  bloc_test: ^9.1.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700

    - family: UrbanistThin
      fonts:
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700

    - family: UrbanistThin
      fonts:
        - asset: assets/fonts/urbanist/Urbanist-Thin.ttf

    - family: UrbanistItalicThin
      fonts:
        - asset: assets/fonts/urbanist/Urbanist-ThinItalic.ttf

    - family: UrbanistLight
      fonts:
        - asset: assets/fonts/urbanist/Urbanist-Light.ttf

    - family: UrbanistRegular
      fonts:
        - asset: assets/fonts/urbanist/Urbanist-Regular.ttf

    - family: UrbanistMedium
      fonts:
        - asset: assets/fonts/urbanist/Urbanist-Medium.ttf

    - family: UrbanistSemiBold
      fonts:
        - asset: assets/fonts/urbanist/Urbanist-SemiBold.ttf

    - family: UrbanistBold
      fonts:
        - asset: assets/fonts/urbanist/Urbanist-Bold.ttf

    # - family: PoppinsThin
    #   fonts:
    #     - asset: assets/fonts/poppins/Poppins-Thin.ttf

    # - family: PoppinsLight
    #   fonts:
    #     - asset: assets/fonts/poppins/Poppins-Light.ttf

    # - family: PoppinsRegular
    #   fonts:
    #     - asset: assets/fonts/poppins/Poppins-Regular.ttf

    # - family: PoppinsMedium
    #   fonts:
    #     - asset: assets/fonts/poppins/Poppins-Medium.ttf

    # - family: PoppinsSemiBold
    #   fonts:
    #     - asset: assets/fonts/poppins/Poppins-SemiBold.ttf

    # - family: PoppinsBold
    #   fonts:
    #     - asset: assets/fonts/poppins/Poppins-Bold.ttf

    - family: PoppinsBlack
      fonts:
        - asset: assets/fonts/poppins/Poppins-Black.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages