name: article_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  connectivity: ^3.0.6
  dartz: ^0.10.1
  dio: ^5.4.2+1
  equatable: ^2.0.5
  floor: ^1.4.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_screenutil: ^5.9.0
  get_it: ^7.7.0
  go_router: ^13.2.5
  google_fonts: ^6.2.1
  http: ^1.2.1
  image_picker: ^1.1.1
  internet_connection_checker: ^1.0.0+1
  intl: ^0.19.0
  meta: ^1.11.0
  retrofit: ^4.1.0
  rxdart: ^0.27.7
  shared_preferences: ^2.2.3
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  retrofit_generator: ^8.1.0
  floor_generator: ^1.4.2
  build_runner: ^2.4.9
  mockito: ^5.4.4
  bloc_test: ^9.1.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/
    - assets/images/card_image.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: MenuAltRight
      fonts:
        - asset: assets/fonts/MenuAltRight.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Regular.ttf
